module_name: Block Permanent Links
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - links
  - permanent links
  - menu
  - link block
description_short: Adds a block which displays permanent links such as sitemap, contact, etc.
description: description.md
images:
  - image-1.png
license: AFL 3.0
